### ISSUE TITLE
mac run fail

### ISSUE THREAD

**Issue by pzee** [SharpnelXu/FGOSimulator#1]
systemOS ：MacOS 12.6

java version:
➜  ~ java --version
java 15.0.2 2021-01-19
Java(TM) SE Runtime Environment (build 15.0.2+7-27)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)

log:
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: /Users/11/Downloads/FGO Simulator v1.04 (jar)/Translations\zh_CN.ini (No such file or directory)
	at yome.fgo.simulator.translation.TranslationManager.setTranslations(TranslationManager.java:38)
	at yome.fgo.simulator.SimulatorMain.main(SimulatorMain.java:21)
Caused by: java.io.FileNotFoundException: /Users/11/Downloads/FGO Simulator v1.04 (jar)/Translations\zh_CN.ini (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:108)
	at yome.fgo.simulator.ResourceManager.readFile(ResourceManager.java:53)
	at yome.fgo.simulator.translation.TranslationManager.setTranslations(TranslationManager.java:36)

**Comment by SharpnelXu** [comment]
Can you make sure this file exists? `Translations/zh_CN.ini`

It's probably due to how Mac and windows handle file path differently...

**Comment by SharpnelXu** [comment]
Attempted a fix, also made it running by **installing javafx sdk** and with the following command through command line:
```
java -p <path to javafx sdk>/lib  --add-modules=javafx.controls,javafx.graphics,javafx.base --add-opens javafx.graphics/com.sun.javafx.util=ALL-UNNAMED --add-opens javafx.base/com.sun.javafx.reflect=ALL-UNNAMED --add-opens javafx.base/com.sun.javafx.beans=ALL-UNNAMED -jar <path to jar>/FGOSimulator.jar
```

I didn't try just running it directly since my Mac has 1.8 runtime...

**Comment by pzee** [comment]
你好，我看了一下，应该是不同系统路径导致的，看一下
https://blog.csdn.net/Dongguabai/article/details/84076256、https://www.cnblogs.com/zyl910/p/java_war_properties_path_easy.html
这部分参考资料能用到没

Yome ***@***.***> 于2022年9月24日周六 04:28写道：

**Comment by SharpnelXu** [comment]
昂，我传了个新版本，已经改了

正确的路径拼接我还没做，因为Windows似乎支持Mac那种拼接（懒）
